### ISSUE TITLE
on_error() missing 1 required positional argument: 'error'

### ISSUE THREAD

**Issue by Microos** [BitMEX/sample-market-maker#166]
- System: `Linux 4.4.0-127-generic #153-Ubuntu SMP Sat May 19 10:58:46 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`
- Python3: `Python 3.5.2`
- Sample-market-maker: `https://github.com/BitMEX/sample-market-maker/releases/tag/v1.5`
- Running Command: `marketmaker`
- Pip Freeze: 
```
bitmex-market-maker==1.5
bitmex-ws==0.3.1
websocket-client==0.52.0
...
```

### Error Message: 

```
2018-10-03 23:18:00,134 - INFO - market_maker - BitMEX Market Maker Version: v1.1

2018-10-03 23:18:00,134 - INFO - ws_thread - Connecting to wss://testnet.bitmex.com/realtime?subscribe=quote:XBTUSD,trade:XBTUSD,instrument,order:XBTUSD,execution:XBTUSD,margin,position
2018-10-03 23:18:00,135 - INFO - ws_thread - Authenticating with API Key.
2018-10-03 23:18:00,136 - INFO - ws_thread - Started thread
2018-10-03 23:18:00,138 - ERROR - _logging - error from callback <bound method BitMEXWebsocket.__on_error of <market_maker.ws.ws_thread.BitMEXWebsocket object at 0x7f93a2b3e160>>: __on_error() missing 1 required positional argument: 'error'
2018-10-03 23:18:00,139 - INFO - ws_thread - Websocket Closed
2018-10-03 23:18:05,142 - ERROR - ws_thread - Couldn't connect to WS! Exiting.
```

- By the way, I am not sure if the version number is wrong. I downloaded the `v1.5` release but got `v1.1` while running.

**Comment by mikeghen** [comment]
I am getting this same error, Python 3.7 on OSX

**Comment by mikeghen** [comment]
@Microos, I fixed this by downgrading to websockets client version 0.47.0

**Comment by anakratis** [comment]
> @Microos, I fixed this by downgrading to websockets client version 0.47.0

You're a life-saver! I fixed this issue, as noted by mikeghen, by running the following commands:

```
sudo pip3 uninstall websocket-client
sudo pip3 install websocket-client==0.47.0
```

**Comment by Microos** [comment]
@mikeghen Thank you. I tried your method. But got another new error. I guess it just doesn't work for me.

```
2018-10-05 12:04:22,657 - INFO - market_maker - BitMEX Market Maker Version: v1.1

2018-10-05 12:04:22,658 - INFO - ws_thread - Connecting to wss://testnet.bitmex.com/realtime?subscribe=quote:XBTUSD,trade:XBTUSD,instrument,order:XBTUSD,execution:XBTUSD,margin,position
2018-10-05 12:04:22,658 - INFO - ws_thread - Authenticating with API Key.
2018-10-05 12:04:22,659 - INFO - ws_thread - Started thread
2018-10-05 12:04:22,662 - ERROR - ws_thread - [Errno 94] Socket type not supported
2018-10-05 12:04:23,660 - ERROR - ws_thread - Couldn't connect to WS! Exiting.
```

Also, I have a fresh new virtual machine with ubuntu 18 installed. And I have the same settings but have `websocket-client==0.53.0` installed.

`Python 3.6.6`
```
bitmex-market-maker==1.5
bitmex-ws==0.3.1
websocket-client==0.53.0
```
Really need to find out what's going wrong.

**Comment by mikeghen** [comment]
did you run: 
```
pip uninstall websocket-client
pip install websocket-client==0.47.0
```

I have not seen that error.

**Comment by tuly1** [comment]
@Microos Were you able to find a solution for this problem? I am getting the exact same error.

**Comment by tuly1** [comment]
Actually I tried what @mikeghen suggested and that fixed the error mentioned in the OP. 

But now I am facing a different error:
```
2018-10-08 22:36:23,929 - INFO - ws_thread - Connected to WS. Waiting for data images, this may take a moment...
2018-10-08 22:36:24,004 - ERROR - _logging - error from callback <bound method BitMEXWebsocket.__on_message of <market_maker.ws.ws_thread.BitMEXWebsocket object at 0x1049e9be0>>: __on_message() takes 2 positional arguments but 3 were given
2018-10-08 22:36:25,639 - ERROR - _logging - error from callback <bound method BitMEXWebsocket.__on_message of <market_maker.ws.ws_thread.BitMEXWebsocket object at 0x1049e9be0>>: __on_message() takes 2 positional arguments but 3 were given
2018-10-08 22:36:26,594 - ERROR - _logging - error from callback <bound method BitMEXWebsocket.__on_message of <market_maker.ws.ws_thread.BitMEXWebsocket object at 0x1049e9be0>>: __on_message() takes 2 positional arguments but 3 were given
2018-10-08 22:36:26,603 - ERROR - _logging - error from callback <bound method BitMEXWebsocket.__on_message of <market_maker.ws.ws_thread.BitMEXWebsocket object at 0x1049e9be0>>: __on_message()
```
Has anyone seen this one before?

**Comment by tuly1** [comment]
I was able to fix this issue without needing to downgrade websocket-client. It seems like an [SSL issue](https://github.com/slackapi/python-slackclient/issues/334) with latest version of websocket-client. I followed the solution below and that did the trick for me.

[How to make Python use CA certificates from Mac OS TrustStore?](https://stackoverflow.com/questions/40684543/how-to-make-python-use-ca-certificates-from-mac-os-truststore)

**Comment by Microos** [comment]
I have found why, And I guess it would be applied to most people.
Go to [here](https://github.com/BitMEX/sample-market-maker/blob/2b77229c952826e3cc5ff1d96448658d2cc9ae5b/market_maker/ws/ws_thread.py#L299) and adding a default value for the parameter `error`.

**Comment by DennyZen** [comment]
@Microos You are right! fixed same error.
 __on_message method should be changed..

**Comment by jjhesk** [comment]
it is fixed with the update of bitmex-ws module.

**Comment by timsned** [comment]
@Microos I'm newish to coding I've changed the __on_message function to include ws as a parameter but am still getting the same error.

2018-10-10 01:57:13,537 - ERROR - _logging - error from callback <bound method BitMEXWebsocket.__on_message of <market_maker.ws.ws_thread.BitMEXWebsocket object at 0x7ff2e327c630>>: __on_message() takes 2 positional arguments but 3 were given

how do I go about adding the default value for error on line 299

Thanks heaps for any help!

**Comment by Microos** [comment]
> @Microos I'm newish to coding I've changed the __on_message function to include ws as a parameter but am still getting the same error.
> 
> 2018-10-10 01:57:13,537 - ERROR - _logging - error from callback <bound method BitMEXWebsocket.__on_message of <market_maker.ws.ws_thread.BitMEXWebsocket object at 0x7ff2e327c630>>: __on_message() takes 2 positional arguments but 3 were given
> 
> how do I go about adding the default value for error on line 299
> 
> Thanks heaps for any help!

@timsned, Hi. To your first question, maybe you can `print` some lines to make sure that you are modifying the exact function. If you are certain about this, then please check if there are 3 parameters, `self, ws, msg`, in your `__on_message()` definition. I got the problem solved after I performed these steps. But I am not 100% sure this solution applies to everyone.

To your second question, simply change the L299 from `def __on_error(self, ws, error):` to `def __on_error(self, ws, error='default error'):`. For more details about python's default arguments, you may refer to [this blog](http://blog.thedigitalcatonline.com/blog/2015/02/11/default-arguments-in-python/).

**Comment by 1HOD** [comment]
Same issue as above today, changed lines 208 and 299 as recommended but same result.  Tried uninstalling bitmex-ws and websocket-client and reinstalling, also installing -r requirments.txt Only clue so far has been that bitmex-ws cannot use the latest version of websocket-client, it requires an earlier version which it reverts to when updating bitmex-ws.

error as it appears:

2018-11-06 17:12:43,198 - ERROR - _logging - error from callback <bound method B
itMEXWebsocket.__on_message of <market_maker.ws.ws_thread.BitMEXWebsocket object
 at 0x02E1CD10>>: __on_message() takes 2 positional arguments but 3 were given

2018-11-06 17:12:43,222 - ERROR - _logging - error from callback <bound method B
itMEXWebsocket.__on_message of <market_maker.ws.ws_thread.BitMEXWebsocket object
 at 0x02E1CD10>>: __on_message() takes 2 positional arguments but 3 were given
2018-11-06 17:12:43,227 - ERROR - _logging - error from callback <bound method B
itMEXWebsocket.__on_message of <market_maker.ws.ws_thread.BitMEXWebsocket object
 at 0x02E1CD10>>: __on_message() takes 2 positional arguments but 3 were given

any thoughts gratefully accepted, might just be a version clash or something simple.

Many thanks!

**Comment by Microos** [comment]
@1HOD Hey. You can try to uninstall the bitmex-ws and then change the two lines mentioned above. See if everything will go correctly. I was coding with pycharm; therefore I can directly jump to the exact callee function and modify it. So you can uninstall the package to remove one possible interference.

**Comment by 1HOD** [comment]
@Microos Hi, thanks for this! tried uninstall bitmex-ws and the changes but no change.

The error seems to suggest those are the exact functions to change but it feels like either those changes aren't read once theyre made or its something else.  any other suggestions? I'll have to look into those functions some more if not.  

Many thanks Microos!

**Comment by Microos** [comment]
@1HOD. Hey man. I guess you are right, neither your modifications weren’t made on the exact functions nor somehow your modifications failed to be loaded. I think you may need to make sure the function you modified is the exact one being called. Inserting some print statement when changing the functions may help. Good luck!

**Comment by 1HOD** [comment]
@Microos Just to update in case anyone has the same, the file I was modifying wasn't the one being read! the file to modify in my case was in the Python\Lib\site-packages folders not the ones I was using...yep...I'm that slow. Thanks for your help, new issue opened for the next problem that probably has the simplest of solutions as well

**Comment by Microos** [comment]
@1HOD I am glad to see that you got things solved. Keep going man :D

**Comment by xenide** [comment]
do you wanna create a pull request for this?

**Comment by vastenly** [comment]
> SSL issue

for me it was fixed by force reinstalling of  certifi 

pip install --upgrade --force-reinstall certifi

**Comment by STRML** [comment]
This is fixed and working with websocket-client 0.56.0.

**Comment by AkshaySapra** [comment]
> This is fixed and working with websocket-client 0.56.0.

Not working for me. I am getting the same errors on websocket-client-0.57.0.

**Comment by yuxiaojian** [comment]
Not working in websocket-client==0.56.0
```
> pip freeze
bitmex-market-maker==1.5
certifi==2020.4.5.1
chardet==3.0.4
future==0.18.2
idna==2.9
requests==2.23.0
six==1.14.0
urllib3==1.25.9
websocket-client==0.56.0
```

**Comment by STRML** [comment]
Thanks - we apologize, 1.5.1 was not uploaded to pypi. So while this was working if you cloned the repository, it was not if you downloaded from `pip` - which is what we recommend in our README, so this was a mistake.

Please reinstall via pip and the problem should be taken care of.

**Comment by starboost** [comment]
probably its becouse 
def on_close(ws, close_status_code, close_msg):
    print(">>>>>>CLOSED")

you must define to close 3 arguments
in my case  it is 4 argument
def on_close(self, ws, close_status_code, close_msg):
    print(">>>>>>CLOSED")
